### ISSUE TITLE
Select All 

### ISSUE THREAD

**Issue by DanOliveira98** [Lupennat/nova-expandable-many#5]
When trying to select all records I receive the following error in the console and it does not select anyone.

TypeError: Cannot read properties of undefined (reading 'preventDefault')
    at Proxy.toggleSelectAllMatching (expandable-many-1.4:2:350575)
    at cn (runtime-core.esm-bundler.js:158:18)
    at un (runtime-core.esm-bundler.js:166:17)
    at On (runtime-core.esm-bundler.js:664:5)
    at onChange.v.<computed>.v.<computed> (app.js?id=1a90ac024e9b60304c2ed24da3ca538e:1:236125)
    at cn (runtime-core.esm-bundler.js:158:18)
    at un (runtime-core.esm-bundler.js:166:17)
    at On (runtime-core.esm-bundler.js:664:5)
    at c (Checkbox.vue.mjs:46:7)
    at cn (runtime-core.esm-bundler.js:158:18)

![image](https://github.com/Lupennat/nova-expandable-many/assets/38472540/5be4060f-fd15-4e61-96da-006683e6f082)

**Comment by Lupennat** [comment]
HI DanOliveira,

Sorry for my late reply.

I was unable to reproduce the error, could you please tell me the versions of nova and expandable many you are using, and if so, whether you have any other third-party packages installed?
